### PR TITLE
Abstract class of PRUDPPacket

### PR DESCRIPTION
**Pull request by andreluis034**
Fixes:
- isHex was in fact verifying if the string was an alphanumeric string of any size, now it checks if it is indeed an hex string and its length is multiple of 2

Changes:
- PRUDPPacket can now be seen as an abstract class and each protocol version should be implemented by extending this class(see version 0 for example) 
- Checking if a flag exists is now done by calling has_xxx_flag which eventually calls a method implemented by the class that extends the abstract class
- Similar to flags, types can now be checked by calling is_xxx
- An instance of PRUDPacket can now be converted to a buffer so it can be sent over the network by calling packet.toBuffer(), the opposite is also possible by calling PRUDPPacketV0.parse(buffer)
- Added jsdoc to all prudp packet related functions

### CODE REVIEW

**Comment by andreluis034** [comment]
To string might be broken (because of missing TYPES and FLAGS vars in the v0 file) I'll fix it first thing tomorrow

**Comment by andreluis034** [comment]
Added @SuperMarioDaBom's checksum calc function

**Comment by RedDuckss** [comment]
Have you considered making classes such as `PRUDPConnectPacket` that extend the base class rather than creating methods for each one?

**Comment by andreluis034** [comment]
@RedDuckss This is the current behavior https://github.com/andreluis034/nex/blob/master/lib/prudp/version0.class.js#L9 I forgot to delete the old functions

**Comment by RedDuckss** [comment]
@andreluis034 I'm aware of that. What I meant was, instead of having that base class (I'm referring to `PRUDPPacketV0`) having methods such as `createConnectPacket` have you considered making another "layer" of packet classes, such as `PRUDPConnectPacket` or `PRUDPConnectPacketV0` that extend `PRUDPPacketV0`. I feel as if working with classes specific for each packet type would make the work flow a bit cleaner, and would clean up the `PRUDPPacketV0` class a bit (by not having it cluttered with methods for each packet type).

**Pull request merged**
